# Site Settings
title: Testing Jekyll
email: andrea.rodriguez.12@sansano.usm.cl
description: >
  Internship CCTVal
baseurl: ""
url: "http://localhost:4000"
github_username:  arodel21
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
